"""
Tests for the janitor-firecrawl skill.

Verifies the deployment artifacts are well-formed and self-consistent,
covering the bugs fixed in `.plans/firecrawl-deploy-fix.md`:

  - deploy.sh exists and is executable, follows the setup-honcho.sh pattern
  - firecrawl-compose.yml uses pre-built images (no broken `build:` paths)
  - Postgres healthcheck uses literal `postgres` user/db (nuq-postgres
    image forces cron.database_name=postgres)
  - The 5 expected services are present
  - The local API key is consistent between deploy.sh and any reference
    in the compose (intentionally `fc janitor-local` with a space)
  - deploy.sh implements `inject_firecrawl_env` (BUG 13 fix)
  - .env.example documents both cloud and self-hosted options

These are pure static checks — no Docker, no network, no subprocess.
Run with: scripts/run_tests.sh tests/skills/test_janitor_firecrawl_skill.py -q
"""
from __future__ import annotations

import os
import re
import stat
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILL_DIR = REPO_ROOT / "skills" / "janitor-firecrawl"
SCRIPTS_DIR = SKILL_DIR / "scripts"
COMPOSE_FILE = SCRIPTS_DIR / "firecrawl-compose.yml"
DEPLOY_SH = SCRIPTS_DIR / "deploy.sh"
SKILL_MD = SKILL_DIR / "SKILL.md"
ENV_EXAMPLE = REPO_ROOT / ".env.example"

EXPECTED_SERVICES = {
    "firecrawl-api",
    "firecrawl-playwright",
    "firecrawl-redis",
    "firecrawl-rabbitmq",
    "firecrawl-postgres",
}

# Per plan + production reality: the local API key is `fc janitor-local`
# (with a space). This matches the upstream Firecrawl image's TEST_API_KEY
# default. See .plans/firecrawl-deploy-fix.md BUG 13.
EXPECTED_LOCAL_API_KEY = "fc janitor-local"


@pytest.fixture(scope="module")
def compose_yaml() -> dict:
    """Load firecrawl-compose.yml as a parsed dict."""
    text = COMPOSE_FILE.read_text()
    return yaml.safe_load(text)


@pytest.fixture(scope="module")
def deploy_text() -> str:
    return DEPLOY_SH.read_text()


# ---------------------------------------------------------------------------
# Test 1: deploy.sh exists and is executable
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    sys.platform == "win32", reason="NTFS carries no executable bit; X_OK is POSIX-only"
)
def test_deploy_sh_exists_and_is_executable() -> None:
    """BUG 5: deploy.sh must exist in the repo and be executable."""
    assert DEPLOY_SH.is_file(), f"deploy.sh missing at {DEPLOY_SH}"
    mode = DEPLOY_SH.stat().st_mode
    assert mode & stat.S_IXUSR, f"deploy.sh not user-executable (mode {oct(mode)})"


# ---------------------------------------------------------------------------
# Test 2: compose uses `image:` not `build:` for postgres (BUG 1)
# ---------------------------------------------------------------------------


def test_postgres_uses_prebuilt_image(compose_yaml: dict) -> None:
    """BUG 1: postgres service must NOT use `build:` with a non-existent path."""
    pg = compose_yaml["services"]["firecrawl-postgres"]
    assert "image" in pg, "firecrawl-postgres missing `image:` key"
    assert pg["image"] == "ghcr.io/firecrawl/nuq-postgres:latest"
    assert "build" not in pg, "firecrawl-postgres must not use `build:`"


def test_all_services_use_image_not_build(compose_yaml: dict) -> None:
    """No service should rely on a `build:` context (all use ghcr.io pre-built)."""
    for name, svc in compose_yaml["services"].items():
        assert "image" in svc, f"{name} missing `image:`"
        assert "build" not in svc, f"{name} should not use `build:`"


# ---------------------------------------------------------------------------
# Test 3: NUQ_RABBITMQ_URL is not inlined with a literal *** (BUG 2)
# ---------------------------------------------------------------------------


def test_no_literal_rabbitmq_password_in_compose(compose_yaml: dict) -> None:
    """BUG 2: NUQ_RABBITMQ_URL must not be inlined with `***` or `changeme`.

    The password is generated by deploy.sh and lives in the env_file
    (`~/.janitor/docker/firecrawl.env`), not in the committed compose.
    """
    raw = COMPOSE_FILE.read_text()
    assert "***" not in raw, "literal `***` found in compose"
    assert (
        "changeme" not in raw
    ), "insecure default `changeme` found in compose — use env_file"
    # The API service must NOT inline NUQ_RABBITMQ_URL — it comes from env_file
    api_env = compose_yaml["services"]["firecrawl-api"].get("environment", [])
    env_blob = " ".join(str(e) for e in api_env)
    assert (
        "NUQ_RABBITMQ_URL" not in env_blob
    ), "NUQ_RABBITMQ_URL should come from env_file, not be inlined in environment:"


# ---------------------------------------------------------------------------
# Test 4: POSTGRES_DB effectively postgres in healthcheck (BUG 4)
# ---------------------------------------------------------------------------


def test_postgres_healthcheck_uses_literal_postgres(compose_yaml: dict) -> None:
    """BUG 4: healthcheck must probe with -U postgres -d postgres.

    Docker does not expand env vars inside `CMD-SHELL` healthchecks, so the
    values must be literal. The nuq-postgres image forces cron.database_name
    to `postgres`, so anything else will fail pg_cron setup.
    """
    pg = compose_yaml["services"]["firecrawl-postgres"]
    hc = pg["healthcheck"]["test"]
    # hc is ["CMD-SHELL", "pg_isready -U postgres -d postgres && ..."]
    cmd = " ".join(hc) if isinstance(hc, list) else str(hc)
    assert "-U postgres" in cmd, f"healthcheck must use literal `-U postgres`: {cmd}"
    assert "-d postgres" in cmd, f"healthcheck must use literal `-d postgres`: {cmd}"
    assert (
        "-d firecrawl" not in cmd
    ), "healthcheck must NOT probe database `firecrawl` (must be `postgres`)"


# ---------------------------------------------------------------------------
# Test 5: 5 expected services present
# ---------------------------------------------------------------------------


def test_compose_defines_expected_services(compose_yaml: dict) -> None:
    services = set(compose_yaml["services"].keys())
    assert services == EXPECTED_SERVICES, (
        f"service set mismatch — expected {EXPECTED_SERVICES}, got {services}"
    )


def test_all_containers_have_janitor_prefix(compose_yaml: dict) -> None:
    """AGENTS.md directive #5: all containers/volumes/networks prefixed `janitor-`."""
    for name, svc in compose_yaml["services"].items():
        cname = svc.get("container_name", "")
        assert cname.startswith("janitor-"), (
            f"{name} container_name '{cname}' missing janitor- prefix"
        )


# ---------------------------------------------------------------------------
# Test 6: deploy.sh hardcodes the local API key matching the compose env
# ---------------------------------------------------------------------------


def test_deploy_sh_uses_consistent_api_key(deploy_text: str) -> None:
    """BUG 13: API key in deploy.sh must be `fc janitor-local` (with space).

    This is the value that ends up both in the env_file's TEST_API_KEY and
    in `~/.janitor/.env`'s FIRECRAWL_API_KEY — they must match exactly or
    Firecrawl returns 401. The space is intentional and matches the
    upstream Firecrawl image default.
    """
    # Variable assignment line in deploy.sh
    m = re.search(r'^FIRECRAWL_LOCAL_API_KEY="([^"]+)"', deploy_text, re.MULTILINE)
    assert m, "FIRECRAWL_LOCAL_API_KEY constant not defined in deploy.sh"
    assert m.group(1) == EXPECTED_LOCAL_API_KEY, (
        f"API key mismatch: expected {EXPECTED_LOCAL_API_KEY!r}, got {m.group(1)!r}"
    )


def test_deploy_sh_does_not_use_hyphenated_key(deploy_text: str) -> None:
    """Sanity: the common-error hyphenated form should not appear anywhere."""
    # Allow it only inside comments; forbid in assignments and string literals
    code_lines = [
        line
        for line in deploy_text.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    code = "\n".join(code_lines)
    assert (
        "fc-janitor-local" not in code
    ), "found `fc-janitor-local` (hyphen) in deploy.sh — must be `fc janitor-local` (space)"


# ---------------------------------------------------------------------------
# Test 7: deploy.sh implements inject_firecrawl_env (BUG 13 fix)
# ---------------------------------------------------------------------------


def test_deploy_sh_implements_env_injection(deploy_text: str) -> None:
    """BUG 13: deploy.sh must inject FIRECRAWL_API_URL/KEY into ~/.janitor/.env."""
    assert "inject_firecrawl_env()" in deploy_text, (
        "inject_firecrawl_env() function missing from deploy.sh"
    )
    assert "FIRECRAWL_API_URL=" in deploy_text
    assert "FIRECRAWL_API_KEY=" in deploy_text


def test_deploy_sh_is_idempotent_for_env_injection(deploy_text: str) -> None:
    """Re-running deploy.sh should not duplicate FIRECRAWL_API_URL/KEY lines."""
    # The function must remove prior FIRECRAWL_API_URL= / FIRECRAWL_API_KEY= lines
    # before appending the new ones.
    assert "grep -v" in deploy_text, (
        "deploy.sh must dedupe prior FIRECRAWL_* lines (idempotency)"
    )
    assert "^FIRECRAWL_API_URL=" in deploy_text
    assert "^FIRECRAWL_API_KEY=" in deploy_text


# ---------------------------------------------------------------------------
# Test 9: .env.example documents both cloud and self-hosted Firecrawl
# ---------------------------------------------------------------------------


def test_env_example_documents_both_firecrawl_options() -> None:
    """BUG 13 doc: .env.example must document cloud API and self-hosted modes."""
    text = ENV_EXAMPLE.read_text()
    # Find the Firecrawl block — from the header line until the next section
    # (a blank line followed by another `# Something` comment for a different
    # service). Lines like `# FIRECRAWL_API_KEY=` look like new sections to a
    # naive `[A-Z]` lookahead, so anchor on the explicit header pattern.
    m = re.search(
        r"^# Firecrawl[^\n]*\n(?:(?!^# FAL\.ai).*\n)*",
        text,
        re.MULTILINE,
    )
    assert m, "Firecrawl section not found in .env.example"
    block = m.group(0)
    assert "FIRECRAWL_API_KEY=" in block, "cloud option (FIRECRAWL_API_KEY) missing"
    assert "FIRECRAWL_API_URL=" in block, "self-hosted option (FIRECRAWL_API_URL) missing"
    assert "127.0.0.1:1974" in block, "default self-hosted URL missing"
    assert "fc janitor-local" in block, "default self-hosted API key missing"


# ---------------------------------------------------------------------------
# Bonus: SKILL.md frontmatter conforms to skill standards
# ---------------------------------------------------------------------------


def test_skill_md_frontmatter_well_formed() -> None:
    """SKILL.md must have valid frontmatter with description ≤ 60 chars."""
    text = SKILL_MD.read_text()
    m = re.search(r"^---\n(.*?)\n---", text, re.DOTALL)
    assert m, "SKILL.md missing YAML frontmatter"
    fm = yaml.safe_load(m.group(1))
    assert fm["name"] == "janitor-firecrawl"
    desc = fm["description"]
    assert isinstance(desc, str)
    assert len(desc) <= 60, f"description too long: {len(desc)} chars"
    assert "platforms" in fm, "platforms field required per skill standards"


def test_skill_md_documents_postgres_constraint() -> None:
    """SKILL.md must call out the POSTGRES_DB=postgres constraint."""
    text = SKILL_MD.read_text()
    assert "POSTGRES_DB" in text, "POSTGRES_DB constraint not documented"
    assert "postgres" in text.lower()


# ---------------------------------------------------------------------------
# Bonus: verify-firecrawl-pgcron.sh uses correct env file and assertions
# ---------------------------------------------------------------------------


def test_verify_pgcron_script_uses_correct_env_file() -> None:
    """BUG 8: verify-firecrawl-pgcron.sh must read docker/firecrawl.env, not .env."""
    script = (REPO_ROOT / "scripts" / "verify-firecrawl-pgcron.sh").read_text()
    assert "docker/firecrawl.env" in script, (
        "must reference ~/.janitor/docker/firecrawl.env (not ~/.janitor/.env)"
    )
    # Must NOT use the old FIRECRAWL_POSTGRES_* var names
    assert "FIRECRAWL_POSTGRES_USER" not in script
    assert "FIRECRAWL_POSTGRES_DB" not in script
    # Must use POSTGRES_USER / POSTGRES_DB
    assert "POSTGRES_USER" in script
    assert "POSTGRES_DB" in script
    # cron.database_name assertion must be 'postgres' not 'firecrawl'
    assert '"postgres"' in script or "== \"postgres\"" in script, (
        "must assert cron.database_name == postgres"
    )
