#!/usr/bin/env bash
set -euo pipefail

# deploy.sh — Deploy NocoDB self-hosted for Janitor
# Bundled in janitor-nocodb skill. Locates the compose file relative to itself.
# Stack: 4 containers (nocodb, worker, postgres, redis) on 127.0.0.1:1980

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
JANITOR_HOME="${HERMES_HOME:-$HOME/.janitor}"
JANITOR_DOCKER_DIR="$JANITOR_HOME/docker"
COMPOSE_FILE="$SCRIPT_DIR/nocodb-compose.yml"
ENV_FILE="$JANITOR_DOCKER_DIR/nocodb.env"
NOCODB_PORT="${NOCODB_PORT:-1980}"

log_info()  { echo -e "\033[1;32m[INFO]\033[0m  $*"; }
log_warn()  { echo -e "\033[1;33m[WARN]\033[0m  $*"; }
log_error() { echo -e "\033[1;31m[ERROR]\033[0m $*"; }

main() {
    check_docker
    generate_env
    ensure_compose_file
    launch
    wait_for_health
    verify_endpoint
    inject_janitor_env
    log_info "NocoDB deployed successfully on http://127.0.0.1:${NOCODB_PORT}"
}

check_docker() {
    if ! docker info >/dev/null 2>&1; then
        log_error "Docker daemon not running. Start it first: sudo systemctl start docker"
        exit 1
    fi
    log_info "Docker daemon OK"
}

generate_env() {
    if [[ -f "$ENV_FILE" ]]; then
        log_warn "Env file already exists: $ENV_FILE (preserving existing credentials)"
        return 0
    fi

    local db_password jwt_secret admin_password

    db_password=$(openssl rand -hex 16)
    jwt_secret=$(openssl rand -hex 32)
    admin_password="Noco$(openssl rand -hex 6 | head -c 10)!2026"

    cat > "$ENV_FILE" <<EOF
# NocoDB — Self-hosted local instance
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# chmod 600 — contains credentials

# PostgreSQL (internal)
NOCODB_DB_NAME=nocodb
NOCODB_DB_USER=nocodb
NOCODB_DB_PASSWORD=${db_password}

# NocoDB core
NC_DB=pg://nocodb-db:5432?u=nocodb&p=${db_password}&d=nocodb
NC_AUTH_JWT_SECRET=${jwt_secret}
NC_CACHE_REDIS_URL=redis://nocodb-redis:6379
NC_JOBS_REDIS_URL=redis://nocodb-redis:6379
NC_ADMIN_EMAIL=janitor@example.com
NC_ADMIN_PASSWORD=${admin_password}
NC_DISABLE_TELE=true
NC_DISABLE_SUPPORT_CHAT=true
NC_DISABLE_ERR_REPORTS=true

# Local network access for webhooks/scripts (localhost only)
NC_WEBHOOK_ALLOW_PRIVATE_NETWORK=true
NC_ALLOW_LOCAL_EXTERNAL_DBS=true
EOF

    chmod 600 "$ENV_FILE"
    log_info "Generated $ENV_FILE (chmod 600)"
    log_info "Admin password: $admin_password"
}

ensure_compose_file() {
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        log_error "Compose file missing: $COMPOSE_FILE"
        exit 1
    fi
    log_info "Compose file OK: $COMPOSE_FILE"
}

launch() {
    log_info "Pulling images..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" pull

    log_info "Starting containers..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d
}

wait_for_health() {
    log_info "Waiting for NocoDB to become healthy (max 180s)..."
    local elapsed=0
    local interval=5
    local timeout=180

    while [[ $elapsed -lt $timeout ]]; do
        local health
        health=$(docker inspect --format='{{.State.Health.Status}}' janitor-nocodb 2>/dev/null || echo "none")

        if [[ "$health" == "healthy" ]]; then
            log_info "NocoDB is healthy (${elapsed}s)"
            return 0
        fi

        echo -n "."
        sleep $interval
        elapsed=$((elapsed + interval))
    done

    echo ""
    log_error "NocoDB did not become healthy within ${timeout}s"
    log_warn "Checking logs..."
    docker logs janitor-nocodb --tail 30 2>&1 || true
    exit 1
}

verify_endpoint() {
    local endpoint="http://127.0.0.1:${NOCODB_PORT}"
    log_info "Verifying endpoint: $endpoint"

    local response
    response=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint" 2>/dev/null || echo "000")

    if [[ "$response" == "200" ]] || [[ "$response" == "302" ]]; then
        log_info "Endpoint OK (HTTP $response)"
    else
        log_warn "Endpoint returned HTTP $response (may still be starting up)"
    fi
}

inject_janitor_env() {
    local janitor_env="$JANITOR_HOME/.env"

    if [[ ! -f "$janitor_env" ]]; then
        touch "$janitor_env"
    fi

    # Remove existing NocoDB entries
    if grep -q "NOCODB_API_URL" "$janitor_env" 2>/dev/null; then
        sed -i '/^# NocoDB/d' "$janitor_env"
        sed -i '/^NOCODB_API_URL/d' "$janitor_env"
        sed -i '/^NOCODB_ADMIN_EMAIL/d' "$janitor_env"
        sed -i '/^NOCODB_ADMIN_PASSWORD/d' "$janitor_env"
    fi

    {
        echo ""
        echo "# NocoDB — Self-hosted local instance"
        echo "NOCODB_API_URL=http://127.0.0.1:${NOCODB_PORT}"
        echo "NOCODB_ADMIN_EMAIL=janitor@example.com"
    } >> "$janitor_env"

    log_info "Injected NOCODB_API_URL into $janitor_env"
}

main "$@"
