#!/bin/bash
set -euo pipefail

JANITOR_HOME="${JANITOR_HOME:-$HOME/.janitor}"
JANITOR_SOURCE_DIR="${JANITOR_SOURCE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}→${NC} $1"; }
log_ok()    { echo -e "${GREEN}✓${NC} $1"; }
log_warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
log_fail()  { echo -e "${RED}✗${NC} $1"; }

check_docker() {
    log_info "Checking Docker..."
    if ! command -v docker >/dev/null 2>&1; then
        log_fail "Docker CLI not found. Install Docker first: https://get.docker.com"
        exit 1
    fi
    if ! docker info >/dev/null 2>&1; then
        log_fail "Docker daemon not running. Start it with: sudo systemctl start docker"
        exit 1
    fi
    log_ok "Docker is available."
}

generate_honcho_env() {
    log_info "Generating honcho.env..."
    local env_file="${JANITOR_HOME}/.env"
    local dst_env="${JANITOR_HOME}/honcho.env"

    if [ ! -f "$env_file" ]; then
        log_warn "No ~/.janitor/.env found — honcho.env will be empty."
        touch "$dst_env"
        return 0
    fi

    set +e
    MINIMAX_KEY=$(grep -v '^#' "$env_file" | grep -m1 '^MINIMAX_API_KEY=' | cut -d '=' -f2-)
    OPENAI_KEY=$(grep -v '^#' "$env_file" | grep -m1 '^OPENAI_API_KEY=' | cut -d '=' -f2-)
    set -e

    {
        echo "# Auto-generated by setup-honcho.sh"
        echo "TRANSPORT=anthropic"
        echo "BASE_URL=https://api.minimax.io/anthropic"
        [ -n "$MINIMAX_KEY" ] && echo "LLM_ANTHROPIC_API_KEY=${MINIMAX_KEY}"
        [ -n "$OPENAI_KEY" ] && echo "LLM_OPENAI_API_KEY=${OPENAI_KEY}"
    } > "$dst_env"

    log_ok "honcho.env written to ${dst_env}"
}

ensure_compose_file() {
    log_info "Setting up compose file..."
    local compose_src="${JANITOR_SOURCE_DIR}/skills/janitor-honcho/scripts/honcho-compose.yml"
    local compose_dst_dir="${JANITOR_HOME}/docker"
    mkdir -p "$compose_dst_dir"

    if [ ! -f "$compose_src" ]; then
        log_fail "Source compose file not found: ${compose_src}"
        exit 1
    fi

    cp -f "$compose_src" "${compose_dst_dir}/honcho-compose.yml"
    log_ok "Compose file updated at ${compose_dst_dir}/honcho-compose.yml"
}

wait_for_health() {
    local url="$1"
    local name="$2"
    local timeout="${3:-60}"
    local elapsed=0
    local interval=5

    log_info "Waiting for $name to be healthy (timeout: ${timeout}s)..."
    while [ $elapsed -lt $timeout ]; do
        if curl -sf "$url" >/dev/null 2>&1; then
            log_ok "$name is healthy"
            return 0
        fi
        sleep $interval
        elapsed=$((elapsed + interval))
        echo -ne "\r  ${CYAN}...${NC} ${elapsed}s / ${timeout}s   "
    done
    echo
    log_warn "$name did not become healthy within ${timeout}s"
    return 1
}

launch_honcho() {
    log_info "Launching Honcho stack..."
    local compose_dir="${JANITOR_HOME}/docker"
    local compose_file="${compose_dir}/honcho-compose.yml"

    if [ ! -f "$compose_file" ]; then
        log_fail "Compose file not found at ${compose_file}"
        exit 1
    fi

    local HONCHO_SRC_DIR="${JANITOR_HOME}/src/honcho"
    if [ ! -d "$HONCHO_SRC_DIR" ]; then
        log_info "Cloning Honcho source code for local build..."
        mkdir -p "${JANITOR_HOME}/src"
        set +e
        git clone https://github.com/plastic-labs/honcho.git "$HONCHO_SRC_DIR" 2>&1
        CLONE_RESULT=$?
        set -e
        if [ $CLONE_RESULT -ne 0 ]; then
            log_warn "Honcho clone failed — stack will not build."
            return 1
        fi
        log_ok "Honcho source cloned to ${HONCHO_SRC_DIR}"
    else
        log_info "Honcho source already present — skipping clone."
    fi

    log_info "Building Honcho from source..."
    set +e
    docker compose --env-file "${JANITOR_HOME}/.env" -f "$compose_file" build 2>&1
    BUILD_RESULT=$?
    set -e

    if [ $BUILD_RESULT -ne 0 ]; then
        log_warn "Docker build had issues — continuing with existing images."
    fi

    log_info "Starting Honcho containers..."
    if ! docker compose --env-file "${JANITOR_HOME}/.env" -f "$compose_file" up -d; then
        log_fail "docker compose up failed for honcho"
        return 1
    fi
    log_ok "Honcho stack started"

    wait_for_health "http://localhost:1973/health" "Honcho" 60 || true
}

install_systemd_unit() {
    log_info "Installing systemd user service for Honcho..."
    local svc_dir="${HOME}/.config/systemd/user"
    local svc_file="${svc_dir}/janitor-honcho.service"
    mkdir -p "$svc_dir"

    cat > "$svc_file" << 'EOF'
[Unit]
Description=Janitor Honcho Memory Stack
After=network.target docker.service
Wants=network.target docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/bin/bash -c 'while ! docker info >/dev/null 2>&1; do sleep 2; done; sleep 5'
WorkingDirectory=%h/.janitor/docker
ExecStart=/bin/bash -c 'cd %h/.janitor/docker && docker compose --env-file %h/.janitor/.env -f honcho-compose.yml up -d'
ExecStop=/bin/bash -c 'cd %h/.janitor/docker && docker compose --env-file %h/.janitor/.env -f honcho-compose.yml down'
TimeoutStartSec=600
TimeoutStopSec=60

[Install]
WantedBy=default.target
EOF

    log_ok "Service file written to ${svc_file}"
    set +e
    systemctl --user daemon-reload 2>/dev/null && systemctl --user enable janitor-honcho.service 2>/dev/null
    set -e
    log_ok "janitor-honcho.service enabled"
}

main() {
    echo -e "${BOLD}═══ Janitor Honcho Setup ═══${NC}"
    check_docker
    generate_honcho_env
    ensure_compose_file
    launch_honcho
    install_systemd_unit
    echo
    log_ok "Honcho setup complete!"
    log_info "Manage with: docker compose --env-file ~/.janitor/.env -f ~/.janitor/docker/honcho-compose.yml [start|stop|logs]"
    log_info "Or: systemctl --user [start|stop] janitor-honcho"
}

main "$@"
